manu-chroma/username-availability-checker

flask/static/only.css, flask/templates/myform.html
- Updated the form to use HTML5 form validation
- Added a message explaining which characters you can type
=> Add validation to form. Fixes #7.

frontend.py
This GET method returns rendered status.html.
This method requires username as variable.
Closes https://github.com/manu-chroma/username-availability-checker/issues/22
=> frontend.py: Add GET method for checking username

static/main.css, templates/status.html
This tooltip shows name of each website
Closes https://github.com/manu-chroma/username-availability-checker/issues/21
=> status.html: Add tooltip to website cards

templates/status.html, username_api.py, websites.yml
This will check the desired username against the required pattern
for each website to ensure the username is possible.
Closes https://github.com/manu-chroma/username-availability-checker/issues/11
=> Add RegEx checking for individual websites

templates/status.html, tests/test_data.yml, tests/test_username_api.py, username_api.py, websites.yml
Addresses https://github.com/manu-chroma/username-availability-checker/issues/20
=> Re-add facebook support

static/css/main.css, templates/status.html, tests/test_data.yml, tests/test_get_avatar.py, tests/test_username_api.py, websites.yml
This will add checkings for OpenHub and DeviantArt.
Uses icon of OpenHub from blackducksoftware/ohloh-ui repo.
Closes https://github.com/manu-chroma/username-availability-checker/issues/24
=> Add support for OpenHub and DeviantArt

tests/test_data.yml, tests/test_username_api.py
This will remove duplicated logic
and put into a function for each test.
Closes https://github.com/manu-chroma/username-availability-checker/issues/36
=> test_username_api.py: Remove duplicated logic

tests/test_username_api.py
Actually, assert in the assert_response function
=> test_username_api.py: Fix assert_response function

static/css/main.css, templates/status.html, tests/test_data.yml, tests/test_get_avatar.py, username_api.py, websites.yml
=> Add support for openSUSE

static/css/main.css
Make border thicker and choose better color
Addresses visibility issues on firefox for
some users.
=> main.css: Tweak form box

cli.py, frontend.py, templates/status.html
This uses websites.yml to create the lists of websites the app can
check. This will make it much easier to add new websites in the
future.
This also fixes the CLI, which was previously broken due to many
changes in the username_api.py file.
Closes #52
=> Determine websites using websites.yml

test-requirements.txt, tests/test_username_api.py, websites.yml
This generator will generate random username that
obeys username rules in websites.yml
Closes https://github.com/manu-chroma/username-availability-checker/issues/47
=> test_username_api: Improve random username generator

.env.copy, .gitignore, .travis.yml, README.md, frontend.py, requirements.txt, templates/status.html
This will set .env file which is
for configuring host and port of backend.
Also README will document this changes.
Closes https://github.com/manu-chroma/username-availability-checker/issues/30
=> Set .env file to distinguish development and product

websites.yml
This adds support for asciinema username
check and implements username patterns.
Closes: https://github.com/manu-chroma/username-availability-checker/issues/51
=> websites.yml: Add support for asciinema

tests/test_data.yml, websites.yml
Closes https://github.com/manu-chroma/username-availability-checker/issues/67
=> fix: Gitlab case sensitivity error

.travis.yml, templates/status.html, test-requirements.txt, tests/test_data.yml, tests/test_username_api.py, username_api.py, websites.yml
This will detect and inform to user if website is down.
It detects the status by checking if constant username
which is probably taken forever is available.
Closes #66 
and some more commits
=> Detect and inform to user if the website is down 

username_api.py, websites.yml
SUMMARY: Added avatar support for Openhub & openSUSE by parsing their respective web pages.
I have fixed both issues, i.e, #62 & #63.
=> Add avatar support for Open Hub & OpenSUSE

.gitignore, tests/test_data.yml, websites.yml
and some minor changes:
* Add `venv/` in `.gitignore`
* Add invalid patterns of tumblr
=> Add support for Medium

templates/form.html, templates/status.html
The `<title>` element determines what appears in browser tabs, so it's helpful to have more descriptive strings than "Welcome" and "Hello".
=> More descriptive html titles

.travis.yml
Option `-vv` shows more detail information of error.
=> .traivis.yml: Change pytest option for travis

.coafile, tests/test_username_api.py, username_api.py
=> Modify Docstring to follow PEP 257

tests/test_data.yml, websites.yml
I refered to https://github.com/keybase/keybase-issues/issues/757#issuecomment-45229307
First website support using add.py :)
Closes #97
=> Add support for keybase

.gitignore, .travis.yml, test-requirements.txt, tests/test_get_avatar.py, username_api.py
* Logs more detail information of the error.
* Save the content of response as html file.
* New function log_response which save the content of response.
* DEBUG option is added.
* Show all html file under /static/errors/ if build fails.
=> Add more loggings for more detail information

static/css/main.css, static/js/generate-usernames.js, templates/form.html
Add functionality that allow users to generate usernames.
Closes https://github.com/manu-chroma/username-availability-checker/issues/111
Uses the following library: https://github.com/awesmubarak/username_generator_cli
Quick screenshot of it:
Definitely need suggestions on how to improve this!
=> Add username generator feature

.coafile, .travis.yml, static/css/main.css
Add StyleLintBear to the list of bears to be run for CSS.
Closes https://github.com/manu-chroma/username-availability-checker/issues/130
Added StyleLintBear to .coafile and added required packages to the ci config file.
=> .coafile: Use StyleLintBear

websites.yml
#Description
Removes the double quotes and added single quotes where quotes are necessary.
#Files Changed
websites.yml
#Tests
Tested on yamllint
#closes https://github.com/manu-chroma/username-availability-checker/issues/116
=> Removes Unnecessary Quotes
